# _config.yaml
title: Our example Helm chart repo
description: A chart repo for storing charts.
theme: minima
url: "https://matofeder.github.io/helm-repo/"
repo_name: helm-repo

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
